@extends('football.layout')
@section('title','Market Analysis')
@section('content')
<h1>{{ $analysis->fixture->homeTeam->name ?? 'Home' }} vs {{ $analysis->fixture->awayTeam->name ?? 'Away' }}</h1>
<div class="grid"><div class="card"><div class="muted">Market</div><strong>{{ $analysis->market_type }}</strong><br>{{ $analysis->selection }}</div><div class="card"><div class="muted">Engineering score</div><div class="stat">{{ $analysis->score }}</div></div><div class="card"><div class="muted">Data quality</div><div class="stat">{{ $analysis->data_quality_score }}</div></div><div class="card"><div class="muted">Status</div><span class="badge {{ $analysis->status }}">{{ str_replace('_',' ',strtoupper($analysis->status)) }}</span></div></div>
<div class="card"><h2>Main risk</h2><p class="risk">{{ $analysis->main_risk ?: 'No specific risk recorded.' }}</p></div>
<div class="grid"><div class="card"><h2>Positive signals</h2><ul>@forelse(($analysis->positive_signals ?? []) as $signal)<li>{{ is_array($signal) ? ($signal['explanation'] ?? json_encode($signal)) : $signal }}</li>@empty<li>No positive signals recorded.</li>@endforelse</ul></div><div class="card"><h2>Contradictions</h2><ul>@forelse(($analysis->contradictions ?? []) as $signal)<li>{{ is_array($signal) ? ($signal['explanation'] ?? json_encode($signal)) : $signal }}</li>@empty<li>No contradictions recorded.</li>@endforelse</ul></div></div>
<div class="card"><h2>Bookmaker odds</h2><p class="muted">Manual odds are optional. Implied probability is bookmaker mathematics and is not the model's confidence.</p><form method="POST" action="{{ route('football.analysis.odds',$analysis) }}" class="row">@csrf<label>Manual odds<input type="number" step="0.01" min="1.01" name="manual_odds" value="{{ $analysis->manual_odds }}"></label><button class="btn">Save odds</button></form>@if($analysis->implied_probability)<p>Implied probability: {{ number_format($analysis->implied_probability*100,1) }}%</p>@endif</div>
@endsection
